# -*- coding: utf-8 -*-
"""ANN Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JUKUx7wbUfa3rX5R1HO-bpNAzsIrodR
"""

import pandas as pd
import torch
import torch.nn as nn

data = pd.read_csv("/content/Student_Performance.csv")

data

"""**Shaping the data**"""

input  = torch.tensor(data['Sleep Hours'].values,  dtype=torch.float32).reshape(-1, 1)
output = torch.tensor(data['Hours Studied'].values, dtype=torch.float32).reshape(-1, 1)

"""**The model (object)**"""

model = nn.Linear(1, 1)

"""**The loss**"""

error = nn.MSELoss()

"""**The optimiser**"""

optim = torch.optim.SGD(model.parameters(), lr=0.001)

"""**The training loop**"""

for i in range(1000):
    pred = model(input)
    loss = error(pred, output)

    optim.zero_grad()
    loss.backward()
    optim.step()

"""**Reading the result**"""

print(model(torch.tensor([[3.0]])))   # predict for 3 hours of sleep
model.weight                          # the learned slope
model.bias                            # the learned intercept

"""**Weight and bias of the model**"""

model.weight

model.bias