# -*- coding: utf-8 -*-
"""Linear_Reg_Pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHa1WPpAa88N1ri-wGcnildQ0jkof2JR
"""

import pandas as pd
import torch
import torch.nn as nn

data = pd.read_csv("/content/Student_Performance.csv")

data

input= torch.tensor(data["Sleep Hours"].values,dtype=torch.float32).reshape(-1,1);
output=torch.tensor(data["Hours Studied"].values,dtype=torch.float32).reshape(-1,1);

model=nn.Linear(1,1)

error=nn.MSELoss()

optim=torch.optim.SGD(model.parameters(),lr=0.001)

for i in range(1000):
  pred=model(input)
  loss = error(pred , output)
  optim.zero_grad()
  loss.backward()
  optim.step()

print(model(torch.tensor([[3.0]])))
model.weight
model.bias