# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evkijUlKLxEOJcvAJjfFfEBjBc5-lDCi
"""

import pandas as pd
import torch
import torch.nn as nn

df = pd.read_csv("/content/Student_Performance.csv")
print(df.head())

input = torch.tensor(df['Sleep Hours'].values,dtype = torch.float32).reshape(-1,1)
output = torch.tensor(df['Hours Studied'].values,dtype = torch.float32).reshape(-1,1)

model = nn.Linear(1,1)
loss = nn.MSELoss()

optim = torch.optim.SGD(model.parameters(),lr = 0.001)

for i in range(1000):
  pred = model(input)
  error = loss(pred,output)
  optim.zero_grad()
  error.backward()
  optim.step()

print(model(torch.tensor([[3.0]])))

model.weight

model.bias