# -*- coding: utf-8 -*-
"""new_linear _regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lukBgx728TJUHkTk2Pv99ofW5d6B_Pqn
"""

import pandas as pd
import torch
import torch.nn as nn

data = pd.read_csv("/content/Student_Performance.csv")
data

input = torch.tensor(data["Sleep Hours"], dtype = torch.float32).reshape(-1, 1)
output = torch.tensor(data["Hours Studied"],dtype = torch.float32).reshape(-1, 1)

model = nn.Linear(1, 1)

error = nn.MSELoss()

optim = torch.optim.SGD(model.parameters(), lr=0.001)

for i in range(1000):
    pred = model(input)
    loss = error(pred, output)

    optim.zero_grad()
    loss.backward()
    optim.step()

print(model(torch.tensor([[3.0]])))
model.weight
model.bias

model.weight

model.bias

